# Generated by Django 5.1.4 on 2025-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainH1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=200, verbose_name='Заголовок на главной стр')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
