# Generated by Django 5.1.4 on 2025-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'Главная страница'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать'), ('about', 'О нас'), ('politics', 'Политика'), ('terms', 'Правила')], max_length=50, unique=True, verbose_name='Страница')),
                ('desc', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Meta-descriptions',
            },
        ),
        migrations.AlterField(
            model_name='mainh1',
            name='page',
            field=models.CharField(choices=[('index', 'Главная страница'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать'), ('about', 'О нас'), ('politics', 'Политика'), ('terms', 'Правила')], max_length=50, unique=True, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='title',
            name='page',
            field=models.CharField(choices=[('index', 'Главная страница'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать'), ('about', 'О нас'), ('politics', 'Политика'), ('terms', 'Правила')], max_length=50, unique=True, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='title',
            name='page_title',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
