# Generated by Django 5.1.4 on 2025-07-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainh1_delete_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainh1',
            options={'verbose_name': 'Заголовок H1', 'verbose_name_plural': 'Заголовок H1'},
        ),
    ]
