# Generated by Django 5.1.4 on 2025-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_description_alter_mainh1_page_alter_title_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AlterField(
            model_name='mainh1',
            name='page',
            field=models.CharField(choices=[('index', 'Главная страница'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать'), ('about', 'О нас')], max_length=50, unique=True, verbose_name='Страница'),
        ),
    ]
