# Generated by Django 5.1.4 on 2025-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mainh1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainh1',
            options={'verbose_name': 'Заголовок H1', 'verbose_name_plural': 'Заголовки H1'},
        ),
        migrations.AddField(
            model_name='mainh1',
            name='page_name',
            field=models.CharField(default='index', max_length=50, unique=True, verbose_name='Название страницы'),
        ),
    ]
