# Generated by Django 5.1.4 on 2025-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mainh1_options_mainh1_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainh1',
            name='page_name',
            field=models.CharField(choices=[('index', 'Главная страница'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать')], max_length=50, unique=True, verbose_name='Название страницы'),
        ),
    ]
