# Generated by Django 5.1.4 on 2025-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mainh1_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'Главная'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать')], max_length=50, verbose_name='Страница')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображения галереи',
                'verbose_name_plural': 'Галерея страницы',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='mainh1',
            name='page_name',
            field=models.CharField(choices=[('index', 'Главная страница'), ('labels', 'Этикетки'), ('packaging', 'Упаковки'), ('bags', 'Пакеты'), ('foils', 'Платинка'), ('flexoprint', 'Флексопечать'), ('about', 'О нас')], max_length=50, unique=True, verbose_name='Название страницы'),
        ),
    ]
