# Generated by Django 5.1.4 on 2025-07-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_galleryimage_alter_mainh1_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
    ]
