# Generated by Django 5.1.4 on 2025-07-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_galleryimage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['page', 'order'], 'verbose_name': 'Изображения', 'verbose_name_plural': 'Галерея'},
        ),
    ]
