# Generated by Django 5.1.4 on 2025-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_galleryimage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AlterField(
            model_name='mainh1',
            name='main_heading',
            field=models.CharField(max_length=200, verbose_name='Заголовок H1'),
        ),
    ]
